services:
  db:
    image: mysql:latest
    container_name: toggers_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toggers-db
      MYSQL_USER: toggers
      MYSQL_PASSWORD: toggers
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
