services:
  users_db:
    image: postgres:latest
    container_name: toggers_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - 3306:3306
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
